### ISSUE TITLE
Issue-added major changes

### ISSUE THREAD

**Issue by kcraftcode** [kentaurse/hashmind#10]
Automated Review Comments
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in src/app/dashboard/ai/page.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/app/dashboard/home/page.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/app/dashboard/settings/page.tsx:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in src/components/navigations/toolbar.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
Issues in src/components/toploader.tsx:
  - (2, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (130, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
Issues in src/context/DataContext.tsx:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
Issues in src/hooks/useLocation.tsx:
  - (2, 'Hardcoded string found')
Issues in yarn.lock:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')

**Comment by jamesleeksc** [comment]
I got it.
