### ISSUE TITLE
Issue-Update user authentication logic

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/hashmind#12]
Automated Review Comments
Issues in index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')

**Comment by ksfactor** [comment]
I got it.
